export const supabaseUrl = 'https://yixaccxaosxsxgsmrjlf.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpeGFjY3hhb3N4c3hnc21yamxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY2ODE0NzIsImV4cCI6MjA0MjI1NzQ3Mn0.gSyRtVIp_i1wvzupJo5wYc6ep7wEOujIFDLbLsDCdMI';

